config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posters do
    member do
      put "like", to: "posters#upvote"
    end
  end
  root to: redirect('/posters')

end

app/models/poster.rb
class Poster < ActiveRecord::Base
    acts_as_votable
    belongs_to :user, :class_name => "User", :foreign_key => "user_id"
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/posters_controller.rb
class PostersController < ApplicationController
  before_action :set_poster, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show]
  
  # GET /posters
  # GET /posters.json
  def index
    @posters = Poster.all
  end

  # GET /posters/1
  # GET /posters/1.json
  def show
  end

  # GET /posters/new
  def new
    @poster = Poster.new
  end

  # POST /posters
  # POST /posters.json
  def create
    @poster = Poster.new(poster_params)

    respond_to do |format|
      if @poster.save
        format.html { redirect_to @poster, notice: 'Poster was successfully created.' }
        format.json { render :show, status: :created, location: @poster }
      else
        format.html { render :new }
        format.json { render json: @poster.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /posters/1/edit
  def edit
  end

  # PATCH/PUT /posters/1
  # PATCH/PUT /posters/1.json
  def update
    respond_to do |format|
      if @poster.update(poster_params)
        format.html { redirect_to @poster, notice: 'Poster was successfully updated.' }
        format.json { render :show, status: :ok, location: @poster }
      else
        format.html { render :edit }
        format.json { render json: @poster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posters/1
  # DELETE /posters/1.json
  def destroy
    @poster.destroy
    respond_to do |format|
      format.html { redirect_to posters_url, notice: 'Poster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @poster.upvote_by current_user
    redirect_to :back
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poster
      @poster = Poster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poster_params
      params.require(:poster).permit(:title, :description, :image, :upvote)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posters_helper.rb
module PostersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html></html>
<head>
  <title>Tweetums</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-brand">
        <%= link_to "Tweetums", root_path %>
        <%= image_tag("twitter.jpg", size: "50x50", :alt => "rss feed") %>
      </div>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-left">
          <li>
            <%= link_to "Tweet It!", new_poster_path %>
          </li>
          <li>
            <%= link_to "Settings", edit_user_registration_path %>
          </li>
          <li>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
          </li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-left">
          <li>
            <%= link_to "Join", new_user_registration_path %>
          </li>
          <li>
            <%= link_to "Log In", new_user_session_path %>
          </li>
        </ul>
      <% end %>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-info" %>
    <% end %>
    <%= yield %>
  </div>
</body>

app/views/posters/_form.html.erb
<%= simple_form_for(@poster) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
  <%= f.input :image, input_html: { class: 'form-control' } %>
  </div>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posters/edit.html.erb
<div class="col-md-8 col-md-offset-2" id="edit_page">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Fix Poster</h1>
      </div>
      <div class="panel-body">
        <div class="current_image">
          <strong class="center">Right Now</strong>
          <%= image_tag @poster.image.url(:medium) %>
        </div>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/posters/index.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="transitions-enabled" id="posters">
    <% @posters.each do |poster| %>
      <div class="box panel panel-default">
        <%= link_to (image_tag poster.image.url, :width => 500, :height => 500), poster %>
        <h2>
          <%= link_to poster.title, poster %>
        </h2>
      </div>
    <% end %>
  </div>
</div>

app/views/posters/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Post Poster</h1>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/posters/show.html.erb
<div class="row" id="poster_show">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel heading poster_image">
        <%= image_tag @poster.image.url, :width => 500, :height => 500 %>
      </div>
      <div class="panel-body">
        <h1>
          <%= @poster.title %>
        </h1>
        <p>
          <%= @poster.description %>
        </p>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-md-6">
            <p class="user">
               Posted by:
              <%= @poster.user_id %>
            </p>
          </div>
          <div class="col-md-6">
            <div class="btn-group pull-right">
              <%= link_to like_poster_path(@poster), method: :put, class: "btn btn-default" do %>
                <span class="glyphicons glyphicons-fire"></span>
                <i class="fa fa-thumbs-up" aria-hidden="true"></i>
                <%= @poster.get_upvotes.size %>
              <% end %>
              <% if user_signed_in? %>
                <%= link_to "Fix Poster", edit_poster_path, class: "btn btn-info" %>
                <%= link_to "Delete", poster_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>